package: tinymce
version: '6.0.0.beta1'
vendor: '6.4.1'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/fortinymce/issues

page:
    title: 'translate:title'
    perm: admin
    subpages:
        main:
            title: 'translate:main'
            subpages:
                demo:
                    title: 'translate:demo'
        profiles:
            title: 'translate:profiles'
        help:
            title: 'translate:help'
            subPath: README.md

pages:
    insertlink:
        title: translate:insertlink
        main: true
        block: system
        popup: true
        hidden: true
        perm: structure/hasStructurePerm
        pjax: true

requires:
    redaxo: '^5.13'
    php: '>=7.4'
conflicts:
    packages:
        tinymce4: '>=0.0.0'
        tinymce5: '>=0.0.0'

installer_ignore:
    - .github
