package: tinymce
version: '8.1.2'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/tinymce/issues

page:
    title: 'translate:title'
    perm: admin
    subpages:
        main:
            title: 'translate:main'
        profiles:
            title: 'translate:profiles'
        snippets:
            title: 'translate:snippets'
        stylesets:
            title: 'translate:stylesets'
        migration:
            title: 'translate:migration'
        help:
            title: 'translate:help'
            subPath: README.md
        devs:
            title: 'translate:devs'
            subPath: DEVS.md

pages:
    insertlink:
        title: translate:insertlink
        main: true
        block: system
        popup: true
        hidden: true
        perm: structure/hasStructurePerm
        pjax: true

requires:
    redaxo: '^5.13'
    php: '>=8.1'

conflicts:
    packages:
        tinymce4: '>=0.0.0'
        tinymce5: '>=0.0.0'

installer_ignore:
    - .github
