package: tinymce5
version: '1.2.13'
vendor: '5.10.2'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/tinymce5/issues

page:
    title: 'translate:title'
    perm: admin
    subpages:
        main:
            title: 'translate:main'
            subpages:
                demo:
                    title: 'translate:demo'
        profiles:
            title: 'translate:profiles'
        help:
            title: 'translate:help'
            subPath: README.md

pages:
    insertlink:
        title: translate:insertlink
        main: true
        block: system
        popup: true
        hidden: true
        perm: structure/hasStructurePerm
        pjax: true

requires:
    redaxo: '^5.10'
    php: '>=7.3'
conflicts:
    packages:
        tinymce4: '>=0.0.0'
