package: tinymce5
version: '1.0.0-beta5'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/tinymce5/issues

page:
    title: 'translate:title'
    perm: admin
    subpages:
        main:
            title: 'translate:main'
            subpages:
                demo:
                    title: 'translate:demo'
#                mblock_demo:
#                    title: 'translate:mblock_demo'
#                    requires:
#                        mblock: '^5.1.0'
        profiles:
            title: 'translate:profiles'
        help:
            title: 'translate:help'
            subPath: README.md

requires:
    redaxo: '^5.7'
    php: '>=7'
conflicts:
    packages:
        tinymce4: '>=0.0.0'
